name: "RELEASE: Check image vulnerabilities"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Full version tag
        required: true
        default: 0.0.0-test-rc.1
        type: string

run-name: ${{ format('Check image vulnerabilities for {0}', inputs.version) }}

jobs:
  run-parameters:
    name: Run parameters
    runs-on: ubuntu-latest
    steps:
      - run: |
          {
            echo "Event: ${{ github.event_name }}"
            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
              echo '```'
              echo "${{ toJSON(inputs) }}"
              echo '```'
            fi
          } >> "$GITHUB_STEP_SUMMARY"

  check-image-vulnerabilities:
    name: Check ${{ matrix.image }}:${{ inputs.version }}
    runs-on: ubuntu-latest
    permissions:
      # Needed for stackrox/central-login to create the JWT token.
      id-token: write
      security-events: write
    strategy:
      matrix:
        image: ["main"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   ref: ${{ github.event.pull_request.head.sha }}

      - name: Central login
        uses: stackrox/central-login@v1
        with:
          endpoint: ${{ vars.ACS_DOGFOODING_CENTRAL_URL }}

      - name: Install roxctl
        uses: stackrox/roxctl-installer-action@v1
        with:
          central-endpoint: ${{ vars.ACS_DOGFOODING_CENTRAL_URL }}
          central-token: ${{ env.ROX_API_TOKEN }}

      - name: Scan images for vulnerabilities
        run: |
          make tag
          roxctl image scan --output=sarif \
            --image="quay.io/rhacs-eng/${{ matrix.image }}:${{ inputs.version }}" \
            > results.sarif

      - name: Upload roxctl scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: ${{ matrix.image }}
          sarif_file: results.sarif
